import type { AnalysisResponse } from '../types/domain';

export function buildSynthesis(analysis: Pick<
  AnalysisResponse,
  'site' | 'overallSuitabilityScore' | 'suitabilityCategory' | 'scorePartial' | 'factors' | 'orientation' | 'terrain' | 'waterRisk' | 'cost'
>): AnalysisResponse['aiSynthesis'] {
  const place = analysis.site.displayName;
  const scoreText = analysis.overallSuitabilityScore === null
    ? 'an overall suitability index could not be calculated'
    : `the suitability index is ${analysis.overallSuitabilityScore}/100 (${analysis.suitabilityCategory})`;
  const partial = analysis.scorePartial ? ' The index is partial because one or more factors were unavailable.' : '';

  const slope = analysis.factors.find((factor) => factor.factor === 'slope');
  const slopeSentence = slope?.available
    ? ` Terrain observation: ${slope.rawValue}.`
    : ' Terrain slope was not available.';

  const recommendations: string[] = [
    `Review a planning orientation near ${analysis.orientation.recommendedCardinal}. This comes from solar geometry${analysis.orientation.windScore === null ? '' : ' and recent wind alignment'}, not from a thermal model.`,
  ];

  if (analysis.terrain.slopePercentage !== null && analysis.terrain.slopePercentage >= 8) {
    recommendations.push('Commission a topographic and geotechnical review before fixing foundation levels. The sampled slope is steep enough to affect earthwork.');
  } else {
    recommendations.push('Still commission a site investigation before structural design. Remote elevation does not replace a survey.');
  }

  if (analysis.waterRisk.riskLevel === 'High Risk' || analysis.waterRisk.riskLevel === 'Moderate Risk') {
    recommendations.push('Ask a drainage engineer to review stormwater because the water/flood-risk indicator is elevated. This is not a flood-zone designation.');
  }

  if (analysis.cost.terrainAdjustmentApplied === false) {
    recommendations.push('Treat the cost range as wider than usual because a terrain multiplier could not be applied.');
  }

  const sustainability: string[] = [];
  if (analysis.orientation.windScore !== null) {
    sustainability.push(analysis.orientation.prevailingWind.summary);
  } else {
    sustainability.push('Wind-driven ventilation guidance was omitted because recent wind data was unavailable.');
  }
  sustainability.push('Rainwater and shading decisions should use the measured rainfall and solar path in this report, not a generic savings percentage.');

  return {
    summary: `For the ${analysis.site.buildingType} proposal at ${place}, ${scoreText}.${partial}${slopeSentence} Guidance below is deterministic and limited to the data that was actually retrieved.`,
    architecturalRecommendations: recommendations,
    sustainabilityNotes: sustainability,
    engineNotice: 'Generated by deterministic geospatial rules, weighted scoring, and astronomical calculations. No language model or machine-learning inference is used.',
  };
}
